name: PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ragnerock-testing
  REGION: us-central1
  ENVIRONMENT: dev
  WORKLOAD_IDENTITY_PROVIDER: projects/843664128510/locations/global/workloadIdentityPools/github-actions-pool/providers/github-ragnerock
  WORKLOAD_SERVICE_ACCOUNT: github-ragnerock@ragnerock-testing.iam.gserviceaccount.com
  PYTHONUNBUFFERED: "1" # prevent output buffering

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install go-task
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash
          apt install task

      - name: Lint 
        run: |
          task lint

      - name: Static check
        run: |
          task check

      - name: Format
        run: |
          task format
        
      - name: Docs
        run: |
          task doc

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run unit tests
        run: |
          task test-unit
        env:
          RAGNEROCK_IS_CI: 'true'