name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Python package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build package
        id: build
        run: |
          uv build --package ragnerock
          uv publish
